package com.example.resepkita.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFad2c00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd34011)
val md_theme_light_onPrimaryContainer = Color(0xFFffffff)
val md_theme_light_secondary = Color(0xFF1b6d24)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFa0f399)
val md_theme_light_onSecondaryContainer = Color(0xFF217128)
val md_theme_light_tertiary = Color(0xFF72554b)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF8d6e63)
val md_theme_light_onTertiaryContainer = Color(0xFFffffff)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFfbf9f5)
val md_theme_light_onBackground = Color(0xFF1b1c1a)
val md_theme_light_surface = Color(0xFFfbf9f5)
val md_theme_light_onSurface = Color(0xFF1b1c1a)
val md_theme_light_surfaceVariant = Color(0xFFe4e2de)
val md_theme_light_onSurfaceVariant = Color(0xFF5a413a)
val md_theme_light_outline = Color(0xFF8f7068)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0ed)
val md_theme_light_inverseSurface = Color(0xFF30312e)
val md_theme_light_inversePrimary = Color(0xFFffb5a0)
val md_theme_light_surfaceTint = Color(0xFFb12d00)
val md_theme_light_outlineVariant = Color(0xFFe3beb5)

// Custom surface containers not natively in standard ColorScheme properties 
val surfaceContainerLowest = Color(0xFFffffff)
val surfaceContainerLow = Color(0xFFf5f3ef)
val surfaceContainer = Color(0xFFefeeea)
val surfaceContainerHigh = Color(0xFFeae8e4)
val surfaceContainerHighest = Color(0xFFe4e2de)